PROJECT = flashwrite

# hier alle zusaetzlichen Softwaremodule angeben
SRCS = ../src/sysf030_init.o
SRCS += ../src/my_printf.o
SRCS += ../src/serial.o


SRC_DIR  = -I./ -I../src -I../include
SRC_DIR += -I../lib/libopencm3/include/libopencm3/stm32
include ../lib/libopencm3.mk
